### ISSUE TITLE
doc typo

### ISSUE THREAD

**Issue by jmellicker** [thestorefront/DataCollection.js#7]
an example for `'.each'` says:

    var dc = new DataCollection([{a: 1, b: 2}, {a: 2, c: 3}]);
    var query = dc.query();
    dc.each(function(row, index) {
        console.log(index + ': ' + row['a'] + ', ' + row['b']);
    });

    // logs
    //    0: 1, 2
    //    1: 2, 3

line 3 should be `'query.each'`, not `'dc.each'`

or, skip line 2 and just write `'dc.query().each'`

**Comment by keithwhor** [comment]
fixed! cheers, thanks for pointing that out :+1:
