### ISSUE TITLE
Is there any possible to simplify the query API?

### ISSUE THREAD

**Issue by ianjiang** [thestorefront/DataCollection.js#8]
Supposed, query API is used more frequently, could it the more clean?

``` javascript
dataset.query().filter()
```

Could use it be:

``` javascript
dataset.filter()
```

**Comment by keithwhor** [comment]
No intention of changing it at present time. `DataCollectionQuery` objects (created by `DataCollection#query`) are queryable subsets of the larger DataCollection and can not do things like adding indices, etc. Would prefer to keep concerns separate. :smile:

**Comment by ianjiang** [comment]
Make sense to me. But we are deeply influenced by jQuery: Write less get more. How about add a query alias: "q". `dataset.q().filter`.

**Comment by keithwhor** [comment]
You're free to create your own fork and write an alias. I prefer code that is readable and easy to reason about upon seeing it for the first time.

**Comment by ianjiang** [comment]
All right.

**Comment by jmfarp2011** [comment]
What if you passed the filter info as a parameter to the .query() method call? Example:

``` javascript
dataset.query({name: "John"})
```

That is how I implemented it in the `graph.database` object of Graph.js:

``` javascript
this.query = function(filters){
    return !!filters ? _entities.spawn().filter(filters) : _entities.spawn();
};
```

`_entities` is a `graph.collection` object, heavy influenced by DataCollection.js.

**Comment by ianjiang** [comment]
You overwrite the query function. Then the original query().filter should not work.

**Comment by ianjiang** [comment]
BTW,  `this.query = function(filters){` if this is current instance, you should create method on prototype, otherwise each instance will have a different function but the functionality is the same.

**Comment by jmfarp2011** [comment]
Yes that should be on the prototype, not the instance.
